print("Calcular fórmula de la pendiente. Introduce los datos.")
print("x1 = ?")
rx1 = float(input())
print("x2 = ?")
rx2 = float(input())
print("y1 = ?")
ry1 = float(input())
print("y2 = ?")
ry2 = float(input())
rM = (ry2 - ry1) / (rx2 - rx1)
print("M = ", end='', flush=True)
print(rM)
