print("Numerador 1 = ", end='', flush=True)
iNum1 = int(input())
print("Denominador 1 = ", end='', flush=True)
iDen1 = int(input())
print("Numerador 2 = ", end='', flush=True)
iNum2 = int(input())
print("Denominador 2 = ", end='', flush=True)
iDen2 = int(input())
iCNSum = iNum1 * iDen2 + iDen1 * iNum2
iCNRes = iNum1 * iDen2 - iDen1 * iNum2
iCNPro = iNum1 * iNum2
iCNDiv = iNum1 * iDen2
iCDDiv = iNum2 * iDen1
iCD = iDen1 * iDen2

print(iNum1, end='', flush=True)
print("/", end='', flush=True)
print(iDen1, end='', flush=True)
print(" + ", end='', flush=True)
print(iNum2, end='', flush=True)
print("/", end='', flush=True)
print(iDen2, end='', flush=True)
print(" = ", end='', flush=True)
print(iCNSum, end='', flush=True)
print("/", end='', flush=True)
print(iCD)

print(iNum1, end='', flush=True)
print("/", end='', flush=True)
print(iDen1, end='', flush=True)
print(" - ", end='', flush=True)
print(iNum2, end='', flush=True)
print("/", end='', flush=True)
print(iDen2, end='', flush=True)
print(" = ", end='', flush=True)
print(iCNRes, end='', flush=True)
print("/", end='', flush=True)
print(iCD)

print(iNum1, end='', flush=True)
print("/", end='', flush=True)
print(iDen1, end='', flush=True)
print(" * ", end='', flush=True)
print(iNum2, end='', flush=True)
print("/", end='', flush=True)
print(iDen2, end='', flush=True)
print(" = ", end='', flush=True)
print(iCNPro, end='', flush=True)
print("/", end='', flush=True)
print(iCD)

print(iNum1, end='', flush=True)
print("/", end='', flush=True)
print(iDen1, end='', flush=True)
print(" / ", end='', flush=True)
print(iNum2, end='', flush=True)
print("/", end='', flush=True)
print(iDen2, end='', flush=True)
print(" = ", end='', flush=True)
print(iCNDiv, end='', flush=True)
print("/", end='', flush=True)
print(iCDDiv)